# not complete!

#"neither can I" hasn't been introduced to the students yet
{
"""I don't like fish.""":["""I don't either.""", """Me neither."""],
"""I don't know how to swim.""":["""I don't either.""", """Me neither."""],
"""I don't like potatoes.""":["""I don't either.""", """Me neither."""],
"""I don't eat donuts at night.""":["""I don't either.""", """Me neither."""],
"""I don't watch scary movies.""":["""I don't either.""", """Me neither."""],
"""I don't yell when I get angry.""":["""I don't either.""", """Me neither."""],
"""I can't ride a bicycle.""":["""I can't either.""", """Me neither."""],
"""I can't swim.""":["""I can't either.""", """Me neither."""],
"""I can't drive a car.""":["""I can't either.""", """Me neither."""],
"""I can't do a pushup.""":["""I can't either.""", """Me neither."""],
"""I can't run faster than a bus.""":["""I can't either.""", """Me neither."""],
"""I can't flap my arms and fly.""":["""I can't either.""", """Me neither."""],
"""I'm not fat.""":["""I'm not either.""", """Me neither."""],
"""I'm not skinny.""":["""I'm not either.""", """Me neither."""],
"""I'm not an angry person.""":["""I'm not either.""", """Me neither."""],
"""I'm not hungry.""":["""I'm not either.""", """Me neither."""],
"""I'm not happy.""":["""I'm not either.""", """Me neither."""],
"""I'm not a purple hippopotamus.""":["""I'm not either.""", """Me neither."""],
"""I like papayas.""":["""I do too.""", """Me too."""],
"""I know how to drive.""":["""I do too.""", """Me too."""],
"""I know how to swim.""":["""I do too.""", """Me too."""],
"""I like oranges.""":["""I do too.""", """Me too."""],
"""I eat cake on Fridays.""":["""I do too.""", """Me too."""],
"""I love comedies.""":["""I do too.""", """Me too."""],
"""I can eat 12 hamburgers at once.""":["""I can too.""", """Me too."""],
"""I can fly an airplane.""":["""I can too.""", """Me too."""],
"""I can write quickly.""":["""I can too.""", """Me too."""],
"""I can run faster than a snail.""":["""I can too.""", """Me too."""],
"""I can calculate faster than a calculator.""":["""I can too.""", """Me too."""],
"""I can swim with my eyes open.""":["""I can too.""", """Me too."""],
"""I'm angry.""":["""I am too.""", """Me too."""],
"""I'm hungry.""":["""I am too.""", """Me too."""],
"""I'm sad.""":["""I am too.""", """Me too."""],
"""I'm busy with work.""":["""I am too.""", """Me too."""],
"""I'm studying right now.""":["""I am too.""", """Me too."""],
"""I'm at school at the moment.""":["""I am too.""", """Me too."""]
}
