# not complete!

#"neither can I" hasn't been introduced to the students yet
{
"""I don't like fish.""":["""I don't either.""", """Me neither."""],
"""I don't know how to swim.""":["""I don't either.""", """Me neither."""],
"""I don't like potatoes.""":["""I don't either.""", """Me neither."""],
"""I don't eat donuts at night.""":["""I don't either.""", """Me neither."""],
"""I don't watch scary movies.""":["""I don't either.""", """Me neither."""],
"""I don't yell when I get angry.""":["""I don't either.""", """Me neither."""],
"""I can't ride a bicycle.""":["""I can't either.""", """Me neither."""],
"""I can't swim.""":["""I can't either.""", """Me neither."""],
"""I can't drive a car.""":["""I can't either.""", """Me neither."""],
"""I can't do a pushup.""":["""I can't either.""", """Me neither."""],
"""I can't run faster than a bus.""":["""I can't either.""", """Me neither."""],
"""I can't flap my arms and fly.""":["""I can't either.""", """Me neither."""],
"""I'm not fat.""":[],
"""I'm not skinny.""":[],
"""I'm not an angry person.""":[],
"""I'm not hungry.""":[],
"""I'm not happy.""":[],
"""I'm not a purple hippopotamus.""":[],
"""I like papayas.""":[],
"""I know how to drive.""":[],
"""I know how to swim.""":[],
"""I like oranges.""":[],
"""I eat cake on Fridays.""":[],
"""I love comedies.""":[],
"""I can eat 12 hamburgers at once.""":[],
"""I can fly an airplane.""":[],
"""I can write quickly.""":[],
"""I can run faster than a snail.""":[],
"""I can calculate faster than a calculator.""":[],
"""I can swim with my eyes open.""":[],
"""I'm angry.""":[],
"""I'm hungry.""":[],
"""I'm sad.""":[],
"""I'm busy with work.""":[],
"""I'm studying right now.""":[],
"""I'm at school at the moment.""":[],
}
