vocab_dict = {"She liked the happy cat.":("happy", "happily", "happy"),
              "He quickly ate his food.":("quick", "quickly", "quickly"),
              "That is a cute puppy!":("cute", "cutely", "cute"),
              "The pozole smells tasty.":("tasty", "tastily", "tasty"),
              "The dead fish looks gross.":("gross", "grossly", "gross"),
              "He speaks slowly.":("slow", "slowly", "slowly"),
              "The girl moves quickly.":("quick", "quickly", "quickly"),
              "I feel angry.":("angry", "angrily", "angry"),
              "The woman looked angrily at the paint stains.":("angry", "angrily", "angrily"),
              "Rosario feels bad about the news.":("bad", "badly", "bad"),
              "Your nose is very senstive. You smell well.":("good", "well", "well"),
              "Nice perfume! You smell good.":("good", "well", "good"),
              "Concha seems sad. She broke up with her boyfriend.":("sad", "sadly", "sad"),
              "Elvia was nervous and spoke very quickly.":("quick", "quickly", "quickly"),
              "Monse rapidly swallowed the taco.":("rapid", "rapidly", "rapidly"),
              "Chivis excitedly watched the new movie.":("excited", "excitedly", "excitedly"),
              "Tizoc rudely cut in line at the cafeteria.":("rude", "rudely", "rudely"),
              "We did a good job on our homework.":("good", "well", "good"),
              "Roberto feels bad.":("bad", "badly", "bad"),
              "This old sushi tastes disgusting.":("disgusting", "disgustingly", "disgusting"),
              "The gross man disgustingly spit on the floor.":("disgusting", "disgustingly", "disgustingly"),
              "Salma Hayek is a beautiful actress.":("beautiful", "beautifully", "beautiful"),
              "Eugenio Derbez acts beautifully.":("beautiful", "beautifully", "beautifully"),
              "She is a slow runner!":("slow", "slowly", "slow"),
              "She drinks thirstily.":("thirsty", "thirstily", "thirstily"),
              "Oliver hungrily ate the burrito.":("hungry", "hungrily", "hungrily"),
              "Five fish swam quickly.":("quick", "quickly", "quickly"),
              "The black crow squawks loudly.":("loud", "loudly", "loudly"),
              "Race cars drive carefully.":("careful", "carefully", "carefully"),
              "Jennifer quietly read her book.":("quiet", "quietly", "quietly"),
              "Luis is a quiet person.":("quiet", "quietly", "quiet"),
              "He is a safe driver.":("safe", "safely", "safe"),
              "Your brother is so kind.":("kind", "kindly", "kind"),
              "I always work hard during the week.":("hard", "hardly", "hard"),
              "Paco did badly on his test.":("bad", "badly", "badly"),
              "It is natural to feel nervous before a job interview.":("nervous", "nervously", "nervous")}
